/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumCategoryCategories } from "./EnumCategoryCategories";
import { IsEnum, IsOptional, ValidateNested } from "class-validator";
import { EducationCreateNestedManyWithoutCategoriesInput } from "./EducationCreateNestedManyWithoutCategoriesInput";
import { Type } from "class-transformer";
import { HealthAndWellnessWhereUniqueInput } from "../../healthAndWellness/base/HealthAndWellnessWhereUniqueInput";
import { ResourcesAndAdviceCreateNestedManyWithoutCategoriesInput } from "./ResourcesAndAdviceCreateNestedManyWithoutCategoriesInput";

@InputType()
class CategoryCreateInput {
  @ApiProperty({
    required: false,
    enum: EnumCategoryCategories,
  })
  @IsEnum(EnumCategoryCategories)
  @IsOptional()
  @Field(() => EnumCategoryCategories, {
    nullable: true,
  })
  categories?:
    | "MentalHealth"
    | "Fitness"
    | "Nutrition"
    | "GeneralHealth"
    | "ChronicCondition"
    | null;

  @ApiProperty({
    required: false,
    type: () => EducationCreateNestedManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => EducationCreateNestedManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => EducationCreateNestedManyWithoutCategoriesInput, {
    nullable: true,
  })
  educations?: EducationCreateNestedManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => HealthAndWellnessWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => HealthAndWellnessWhereUniqueInput)
  @IsOptional()
  @Field(() => HealthAndWellnessWhereUniqueInput, {
    nullable: true,
  })
  healthAndWellnesses?: HealthAndWellnessWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ResourcesAndAdviceCreateNestedManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => ResourcesAndAdviceCreateNestedManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => ResourcesAndAdviceCreateNestedManyWithoutCategoriesInput, {
    nullable: true,
  })
  resourcesAndAdvices?: ResourcesAndAdviceCreateNestedManyWithoutCategoriesInput;
}

export { CategoryCreateInput as CategoryCreateInput };
