import { Comment } from "../comment/Comment";
import { CommunitySupport } from "../communitySupport/CommunitySupport";
import { DailyActivity } from "../dailyActivity/DailyActivity";
import { Discussion } from "../discussion/Discussion";
import { Education } from "../education/Education";
import { FinancialAssistance } from "../financialAssistance/FinancialAssistance";
import { HealthActivity } from "../healthActivity/HealthActivity";
import { HealthAndWellness } from "../healthAndWellness/HealthAndWellness";
import { LocalEvent } from "../localEvent/LocalEvent";
import { MedicalPractitioner } from "../medicalPractitioner/MedicalPractitioner";
import { MedicationOrder } from "../medicationOrder/MedicationOrder";
import { ResourcesAndAdvice } from "../resourcesAndAdvice/ResourcesAndAdvice";
import { Review } from "../review/Review";
import { JsonValue } from "type-fest";
import { WellnessGoal } from "../wellnessGoal/WellnessGoal";

export type User = {
  comments?: Array<Comment>;
  communitySupports?: Array<CommunitySupport>;
  createdAt: Date;
  dailyActivities?: Array<DailyActivity>;
  discussions?: Array<Discussion>;
  educations?: Array<Education>;
  email: string | null;
  financialAssistances?: Array<FinancialAssistance>;
  firstName: string | null;
  healthActivities?: Array<HealthActivity>;
  healthAndWellnesses?: Array<HealthAndWellness>;
  id: string;
  isActive: boolean | null;
  lastName: string | null;
  localEvents?: Array<LocalEvent>;
  medicalPractitioners?: Array<MedicalPractitioner>;
  medicationOrders?: Array<MedicationOrder>;
  resourcesAndAdvices?: Array<ResourcesAndAdvice>;
  reviews?: Array<Review>;
  roles: JsonValue;
  updatedAt: Date;
  username: string;
  wellnessGoals?: Array<WellnessGoal>;
};
