import { CommentUpdateManyWithoutUsersInput } from "./CommentUpdateManyWithoutUsersInput";
import { CommunitySupportUpdateManyWithoutUsersInput } from "./CommunitySupportUpdateManyWithoutUsersInput";
import { DailyActivityUpdateManyWithoutUsersInput } from "./DailyActivityUpdateManyWithoutUsersInput";
import { DiscussionUpdateManyWithoutUsersInput } from "./DiscussionUpdateManyWithoutUsersInput";
import { EducationUpdateManyWithoutUsersInput } from "./EducationUpdateManyWithoutUsersInput";
import { FinancialAssistanceUpdateManyWithoutUsersInput } from "./FinancialAssistanceUpdateManyWithoutUsersInput";
import { HealthActivityUpdateManyWithoutUsersInput } from "./HealthActivityUpdateManyWithoutUsersInput";
import { HealthAndWellnessUpdateManyWithoutUsersInput } from "./HealthAndWellnessUpdateManyWithoutUsersInput";
import { LocalEventUpdateManyWithoutUsersInput } from "./LocalEventUpdateManyWithoutUsersInput";
import { MedicalPractitionerUpdateManyWithoutUsersInput } from "./MedicalPractitionerUpdateManyWithoutUsersInput";
import { MedicationOrderUpdateManyWithoutUsersInput } from "./MedicationOrderUpdateManyWithoutUsersInput";
import { ResourcesAndAdviceUpdateManyWithoutUsersInput } from "./ResourcesAndAdviceUpdateManyWithoutUsersInput";
import { ReviewUpdateManyWithoutUsersInput } from "./ReviewUpdateManyWithoutUsersInput";
import { InputJsonValue } from "../../types";
import { WellnessGoalUpdateManyWithoutUsersInput } from "./WellnessGoalUpdateManyWithoutUsersInput";

export type UserUpdateInput = {
  comments?: CommentUpdateManyWithoutUsersInput;
  communitySupports?: CommunitySupportUpdateManyWithoutUsersInput;
  dailyActivities?: DailyActivityUpdateManyWithoutUsersInput;
  discussions?: DiscussionUpdateManyWithoutUsersInput;
  educations?: EducationUpdateManyWithoutUsersInput;
  email?: string | null;
  financialAssistances?: FinancialAssistanceUpdateManyWithoutUsersInput;
  firstName?: string | null;
  healthActivities?: HealthActivityUpdateManyWithoutUsersInput;
  healthAndWellnesses?: HealthAndWellnessUpdateManyWithoutUsersInput;
  isActive?: boolean | null;
  lastName?: string | null;
  localEvents?: LocalEventUpdateManyWithoutUsersInput;
  medicalPractitioners?: MedicalPractitionerUpdateManyWithoutUsersInput;
  medicationOrders?: MedicationOrderUpdateManyWithoutUsersInput;
  password?: string;
  resourcesAndAdvices?: ResourcesAndAdviceUpdateManyWithoutUsersInput;
  reviews?: ReviewUpdateManyWithoutUsersInput;
  roles?: InputJsonValue;
  username?: string;
  wellnessGoals?: WellnessGoalUpdateManyWithoutUsersInput;
};
