import { CommentListRelationFilter } from "../comment/CommentListRelationFilter";
import { CommunitySupportListRelationFilter } from "../communitySupport/CommunitySupportListRelationFilter";
import { DailyActivityListRelationFilter } from "../dailyActivity/DailyActivityListRelationFilter";
import { DiscussionListRelationFilter } from "../discussion/DiscussionListRelationFilter";
import { EducationListRelationFilter } from "../education/EducationListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { FinancialAssistanceListRelationFilter } from "../financialAssistance/FinancialAssistanceListRelationFilter";
import { HealthActivityListRelationFilter } from "../healthActivity/HealthActivityListRelationFilter";
import { HealthAndWellnessListRelationFilter } from "../healthAndWellness/HealthAndWellnessListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { LocalEventListRelationFilter } from "../localEvent/LocalEventListRelationFilter";
import { MedicalPractitionerListRelationFilter } from "../medicalPractitioner/MedicalPractitionerListRelationFilter";
import { MedicationOrderListRelationFilter } from "../medicationOrder/MedicationOrderListRelationFilter";
import { ResourcesAndAdviceListRelationFilter } from "../resourcesAndAdvice/ResourcesAndAdviceListRelationFilter";
import { ReviewListRelationFilter } from "../review/ReviewListRelationFilter";
import { WellnessGoalListRelationFilter } from "../wellnessGoal/WellnessGoalListRelationFilter";

export type UserWhereInput = {
  comments?: CommentListRelationFilter;
  communitySupports?: CommunitySupportListRelationFilter;
  dailyActivities?: DailyActivityListRelationFilter;
  discussions?: DiscussionListRelationFilter;
  educations?: EducationListRelationFilter;
  email?: StringNullableFilter;
  financialAssistances?: FinancialAssistanceListRelationFilter;
  firstName?: StringNullableFilter;
  healthActivities?: HealthActivityListRelationFilter;
  healthAndWellnesses?: HealthAndWellnessListRelationFilter;
  id?: StringFilter;
  isActive?: BooleanNullableFilter;
  lastName?: StringNullableFilter;
  localEvents?: LocalEventListRelationFilter;
  medicalPractitioners?: MedicalPractitionerListRelationFilter;
  medicationOrders?: MedicationOrderListRelationFilter;
  resourcesAndAdvices?: ResourcesAndAdviceListRelationFilter;
  reviews?: ReviewListRelationFilter;
  username?: StringFilter;
  wellnessGoals?: WellnessGoalListRelationFilter;
};
